[package]
name = "plonky2_compute_shuffled_index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "*"
plonky2 = "0.1.4"